### ISSUE TITLE
Plugins - How to Install and Persist

### ISSUE THREAD

**Issue by marlinhares** [indiehosters/discourse#16]
We are testing this setup before decide for a production one.

How can we set discourse plugins to run on this setup?

**Comment by pierreozoux** [comment]
currently, you have to hanlde them manually.
I'm thinking a nice and easy way would be to ship basic plugins here.
What are the plugins you want to add?

**Comment by pierreozoux** [comment]
(I currently mount a plugin directoy and run the assets script)

**Comment by brospars** [comment]
@pierreozoux Could you elaborate please ? You mount it as a volume ?

I tried this but it doesn't seem to work
```
app:
    image: indiehosters/discourse:${DISCOURSE_VERSION:-2.2.0.beta4}
    volumes:
    - ./data/assets:/home/discourse/discourse/public/assets
    - ./data/uploads:/home/discourse/discourse/public/uploads
    - ./data/backups:/home/discourse/discourse/public/backups
    - ./data/plugins:/home/discourse/discourse/plugins
```
